"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { signOut } from "next-auth/react";
import {
  RefreshCw,
  AlertTriangle,
  Plus,
  Clock,
  CheckCircle2,
  Eye,
  ChevronDown,
  ChevronRight,
  MessageSquare,
  ArrowUpDown,
  Shield,
  LogOut,
  X,
  Send,
  Link2,
} from "lucide-react";
import { formatDistanceToNow } from "date-fns";

// Known 3rd party providers the ops team interacts with
const PROVIDERS = [
  "Fireblocks",
  "Ledger",
  "GX",
  "Komainu",
  "Notabene",
  "Chainalysis",
  "Elliptic",
  "Copper",
  "Other",
];

const SEVERITY_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  critical: { label: "Critical", color: "text-red-400", bg: "bg-red-500/10 border-red-500/20" },
  high: { label: "High", color: "text-orange-400", bg: "bg-orange-500/10 border-orange-500/20" },
  medium: { label: "Medium", color: "text-amber-400", bg: "bg-amber-500/10 border-amber-500/20" },
  low: { label: "Low", color: "text-blue-400", bg: "bg-blue-500/10 border-blue-500/20" },
};

const STATUS_CONFIG: Record<string, { label: string; color: string; icon: typeof Clock }> = {
  active: { label: "Active", color: "text-red-400", icon: AlertTriangle },
  monitoring: { label: "Monitoring", color: "text-amber-400", icon: Eye },
  resolved: { label: "Resolved", color: "text-emerald-400", icon: CheckCircle2 },
};

interface IncidentData {
  id: string;
  title: string;
  provider: string;
  severity: string;
  status: string;
  description: string;
  impact: string;
  startedAt: string;
  resolvedAt: string | null;
  reportedBy: { id: string; name: string };
  resolvedBy: { id: string; name: string } | null;
  linkedThreads: Array<{ id: string; subject: string; status: string; priority: string; clientOrPartnerTag?: string }>;
  linkedTransactionIds: string[];
  updates: Array<{ id: string; content: string; type: string; createdAt: string }>;
  alerts: Array<{
    id: string;
    type: string;
    priority: string;
    message: string;
    status: string;
    createdAt: string;
    thread: { id: string; subject: string } | null;
  }>;
}

/**
 * 3rd Party Incidents page.
 *
 * Tracks outages and issues with external providers (Fireblocks, Ledger, GX, etc.)
 * that affect ops. Each incident can link to:
 *   - SLA-breached comms threads (explains why SLAs were missed)
 *   - Failed/rejected transactions (correlates transaction failures to root cause)
 *   - Alerts generated by the system
 * Incident timeline shows updates, escalations, and resolution.
 */
export default function IncidentsPage() {
  const [incidents, setIncidents] = useState<IncidentData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState<string>("");
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // Create form state
  const [newTitle, setNewTitle] = useState("");
  const [newProvider, setNewProvider] = useState("Fireblocks");
  const [newSeverity, setNewSeverity] = useState("medium");
  const [newDescription, setNewDescription] = useState("");
  const [newImpact, setNewImpact] = useState("");

  // Update form state
  const [updateText, setUpdateText] = useState("");
  const [updatingId, setUpdatingId] = useState<string | null>(null);

  useEffect(() => {
    fetchIncidents();
  }, [statusFilter]);

  async function fetchIncidents() {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams();
      if (statusFilter) params.set("status", statusFilter);
      const res = await fetch(`/api/incidents?${params}`);
      const json = await res.json();
      if (json.success) {
        setIncidents(json.data);
      } else {
        setError(json.error || "Failed to load incidents");
      }
    } catch {
      setError("Network error — could not reach server");
    } finally {
      setLoading(false);
    }
  }

  async function handleCreate(e: React.FormEvent) {
    e.preventDefault();
    if (!newTitle || !newProvider) return;
    setSubmitting(true);
    try {
      const res = await fetch("/api/incidents", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: newTitle,
          provider: newProvider,
          severity: newSeverity,
          description: newDescription,
          impact: newImpact,
        }),
      });
      const json = await res.json();
      if (json.success) {
        setShowCreateForm(false);
        setNewTitle("");
        setNewDescription("");
        setNewImpact("");
        fetchIncidents();
      }
    } catch {
      // handled by error state
    } finally {
      setSubmitting(false);
    }
  }

  async function handleStatusChange(id: string, newStatus: string) {
    await fetch("/api/incidents", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        id,
        status: newStatus,
        update: newStatus === "resolved"
          ? "Incident resolved"
          : newStatus === "monitoring"
            ? "Moved to monitoring"
            : "Status updated",
        updateType: newStatus === "resolved" ? "resolution" : "update",
      }),
    });
    fetchIncidents();
  }

  async function handleAddUpdate(id: string) {
    if (!updateText.trim()) return;
    setUpdatingId(id);
    await fetch("/api/incidents", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, update: updateText }),
    });
    setUpdateText("");
    setUpdatingId(null);
    fetchIncidents();
  }

  const activeCount = incidents.filter((i) => i.status === "active").length;
  const monitoringCount = incidents.filter((i) => i.status === "monitoring").length;

  return (
    <div className="space-y-4 md:space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-foreground flex items-center gap-2">
            <AlertTriangle size={24} className="text-primary" />
            3rd Party Incidents
          </h1>
          <p className="text-xs md:text-sm text-muted-foreground mt-1">
            Track external provider outages and their impact on operations
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowCreateForm(true)}
            className="flex items-center gap-2 px-3 py-2 text-sm bg-primary text-primary-foreground rounded-lg hover:bg-primary/90"
          >
            <Plus size={16} />
            Raise Incident
          </button>
          <button
            onClick={fetchIncidents}
            className="flex items-center gap-2 px-3 py-2 text-sm text-muted-foreground bg-card border border-border rounded-lg hover:bg-accent/50"
          >
            <RefreshCw size={16} className={loading ? "animate-spin" : ""} />
          </button>
        </div>
      </div>

      {/* Error state */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/20 rounded-xl p-6 text-center">
          <AlertTriangle size={24} className="mx-auto mb-3 text-red-400" />
          <p className="text-sm text-red-400 font-medium mb-1">{error}</p>
          <p className="text-xs text-muted-foreground mb-4">If this persists, try signing out and back in.</p>
          <div className="flex items-center justify-center gap-3">
            <button onClick={fetchIncidents} className="inline-flex items-center gap-2 px-4 py-2 text-sm bg-card border border-border rounded-lg hover:bg-accent/50 text-foreground">
              <RefreshCw size={14} /> Retry
            </button>
            <button onClick={() => signOut({ callbackUrl: "/login" })} className="inline-flex items-center gap-2 px-4 py-2 text-sm bg-red-500/10 border border-red-500/20 rounded-lg hover:bg-red-500/20 text-red-400">
              <LogOut size={14} /> Sign Out
            </button>
          </div>
        </div>
      )}

      {/* Summary + filter */}
      <div className="flex flex-wrap items-center gap-3 bg-card rounded-xl border border-border p-3 md:p-4">
        <div className="flex gap-1 bg-muted/50 rounded-lg p-1">
          {[
            { key: "", label: "All", count: incidents.length },
            { key: "active", label: "Active", count: activeCount },
            { key: "monitoring", label: "Monitoring", count: monitoringCount },
            { key: "resolved", label: "Resolved", count: incidents.length - activeCount - monitoringCount },
          ].map((tab) => (
            <button
              key={tab.key}
              onClick={() => setStatusFilter(tab.key)}
              className={`px-3 py-1.5 text-sm rounded-md transition-colors whitespace-nowrap ${
                statusFilter === tab.key
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {tab.label}
              {tab.count > 0 && (
                <span className={`ml-1.5 text-xs ${statusFilter === tab.key ? "text-primary-foreground/80" : tab.key === "active" && tab.count > 0 ? "text-red-400" : "text-muted-foreground"}`}>
                  ({tab.count})
                </span>
              )}
            </button>
          ))}
        </div>
      </div>

      {/* Create form modal */}
      {showCreateForm && (
        <div className="bg-card rounded-xl border border-border p-5">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold text-foreground">Raise New Incident</h3>
            <button onClick={() => setShowCreateForm(false)} className="text-muted-foreground hover:text-foreground">
              <X size={16} />
            </button>
          </div>
          <form onSubmit={handleCreate} className="space-y-3">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="text-xs font-medium text-muted-foreground block mb-1">Title</label>
                <input
                  type="text"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g. Fireblocks signing service down"
                  required
                  className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-muted-foreground block mb-1">Provider</label>
                  <select
                    value={newProvider}
                    onChange={(e) => setNewProvider(e.target.value)}
                    className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
                  >
                    {PROVIDERS.map((p) => (
                      <option key={p} value={p}>{p}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="text-xs font-medium text-muted-foreground block mb-1">Severity</label>
                  <select
                    value={newSeverity}
                    onChange={(e) => setNewSeverity(e.target.value)}
                    className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
                  >
                    <option value="critical">Critical</option>
                    <option value="high">High</option>
                    <option value="medium">Medium</option>
                    <option value="low">Low</option>
                  </select>
                </div>
              </div>
            </div>
            <div>
              <label className="text-xs font-medium text-muted-foreground block mb-1">Description</label>
              <textarea
                value={newDescription}
                onChange={(e) => setNewDescription(e.target.value)}
                placeholder="What is the issue? Any error messages or status page info..."
                rows={2}
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-muted-foreground block mb-1">Operational Impact</label>
              <textarea
                value={newImpact}
                onChange={(e) => setNewImpact(e.target.value)}
                placeholder="e.g. Cannot process outbound ETH transactions, client withdrawals delayed..."
                rows={2}
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>
            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setShowCreateForm(false)}
                className="px-4 py-2 text-sm text-muted-foreground border border-border rounded-lg hover:bg-accent/50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={submitting || !newTitle}
                className="px-4 py-2 text-sm bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 disabled:opacity-50"
              >
                {submitting ? "Creating..." : "Raise Incident"}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Incident list */}
      {loading && incidents.length === 0 ? (
        <div className="bg-card rounded-xl border border-border p-12 text-center text-muted-foreground">
          <RefreshCw size={24} className="mx-auto mb-3 animate-spin" />
          Loading incidents...
        </div>
      ) : incidents.length === 0 ? (
        <div className="bg-card rounded-xl border border-border p-12 text-center">
          <CheckCircle2 size={24} className="mx-auto mb-3 text-emerald-400" />
          <p className="text-sm text-muted-foreground">
            {statusFilter ? `No ${statusFilter} incidents.` : "No incidents recorded. All systems operational."}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {incidents.map((inc) => {
            const isExpanded = expandedId === inc.id;
            const sevConfig = SEVERITY_CONFIG[inc.severity] || SEVERITY_CONFIG.medium;
            const statusConf = STATUS_CONFIG[inc.status] || STATUS_CONFIG.active;
            const StatusIcon = statusConf.icon;
            const duration = inc.resolvedAt
              ? `${Math.round((new Date(inc.resolvedAt).getTime() - new Date(inc.startedAt).getTime()) / 3_600_000)}h`
              : formatDistanceToNow(new Date(inc.startedAt), { addSuffix: false });

            return (
              <div key={inc.id} className={`rounded-xl border transition-colors ${inc.status === "active" ? sevConfig.bg : "bg-card border-border"}`}>
                {/* Header row */}
                <button
                  onClick={() => setExpandedId(isExpanded ? null : inc.id)}
                  className="w-full flex items-center gap-3 p-4 text-left"
                >
                  <div className="shrink-0">
                    {isExpanded ? <ChevronDown size={16} className="text-muted-foreground" /> : <ChevronRight size={16} className="text-muted-foreground" />}
                  </div>

                  <StatusIcon size={16} className={`shrink-0 ${statusConf.color}`} />

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="text-sm font-semibold text-foreground">{inc.title}</p>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${sevConfig.color} ${sevConfig.bg}`}>
                        {sevConfig.label}
                      </span>
                      <span className="text-xs px-2 py-0.5 rounded-full bg-muted text-muted-foreground">
                        {inc.provider}
                      </span>
                    </div>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      Reported by {inc.reportedBy.name} · {formatDistanceToNow(new Date(inc.startedAt), { addSuffix: true })}
                      {inc.resolvedAt && ` · Resolved after ${duration}`}
                    </p>
                  </div>

                  {/* Linked counts */}
                  <div className="hidden sm:flex items-center gap-3 shrink-0 text-xs">
                    {inc.linkedThreads.length > 0 && (
                      <div className="flex items-center gap-1 text-muted-foreground">
                        <MessageSquare size={12} />
                        {inc.linkedThreads.length}
                      </div>
                    )}
                    {inc.linkedTransactionIds.length > 0 && (
                      <div className="flex items-center gap-1 text-muted-foreground">
                        <ArrowUpDown size={12} />
                        {inc.linkedTransactionIds.length}
                      </div>
                    )}
                    {inc.alerts.length > 0 && (
                      <div className="flex items-center gap-1 text-muted-foreground">
                        <Shield size={12} />
                        {inc.alerts.length}
                      </div>
                    )}
                  </div>

                  <span className={`text-xs font-medium shrink-0 ${statusConf.color}`}>
                    {statusConf.label}
                  </span>
                </button>

                {/* Expanded detail */}
                {isExpanded && (
                  <div className="px-4 pb-4 space-y-4">
                    {/* Description & Impact */}
                    {(inc.description || inc.impact) && (
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        {inc.description && (
                          <div className="bg-background/50 rounded-lg p-3">
                            <p className="text-xs font-medium text-muted-foreground mb-1">Description</p>
                            <p className="text-sm text-foreground">{inc.description}</p>
                          </div>
                        )}
                        {inc.impact && (
                          <div className="bg-background/50 rounded-lg p-3">
                            <p className="text-xs font-medium text-muted-foreground mb-1">Operational Impact</p>
                            <p className="text-sm text-foreground">{inc.impact}</p>
                          </div>
                        )}
                      </div>
                    )}

                    {/* Linked threads (SLA breaches) */}
                    {inc.linkedThreads.length > 0 && (
                      <div>
                        <p className="text-xs font-medium text-muted-foreground mb-2 flex items-center gap-1">
                          <Link2 size={12} /> Linked Threads
                        </p>
                        <div className="space-y-1.5">
                          {inc.linkedThreads.map((t) => (
                            <Link
                              key={t.id}
                              href={`/comms/thread/${t.id}`}
                              className="flex items-center gap-2 p-2 rounded-lg bg-background/50 hover:bg-accent/30 transition-colors text-sm"
                            >
                              <span className={`text-xs px-1.5 py-0.5 rounded font-medium ${t.priority === "P0" ? "bg-red-500/10 text-red-400" : t.priority === "P1" ? "bg-orange-500/10 text-orange-400" : "bg-muted text-muted-foreground"}`}>
                                {t.priority}
                              </span>
                              <span className="text-foreground truncate flex-1">{t.subject}</span>
                              {t.clientOrPartnerTag && <span className="text-xs text-muted-foreground">{t.clientOrPartnerTag}</span>}
                              <span className="text-xs text-muted-foreground">{t.status}</span>
                            </Link>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Linked transactions */}
                    {inc.linkedTransactionIds.length > 0 && (
                      <div>
                        <p className="text-xs font-medium text-muted-foreground mb-2 flex items-center gap-1">
                          <ArrowUpDown size={12} /> Linked Transactions
                        </p>
                        <div className="flex flex-wrap gap-2">
                          {inc.linkedTransactionIds.map((txId) => (
                            <span key={txId} className="text-xs px-2 py-1 rounded bg-background/50 text-foreground font-mono">
                              {txId.length > 16 ? `${txId.slice(0, 8)}...${txId.slice(-8)}` : txId}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Linked alerts (SLA breaches linked to this incident) */}
                    {inc.alerts.length > 0 && (
                      <div>
                        <p className="text-xs font-medium text-muted-foreground mb-2 flex items-center gap-1">
                          <Shield size={12} /> Related Alerts
                        </p>
                        <div className="space-y-1.5">
                          {inc.alerts.map((a) => (
                            <div key={a.id} className="flex items-center gap-2 p-2 rounded-lg bg-background/50 text-xs">
                              <span className={`px-1.5 py-0.5 rounded font-medium ${a.priority === "P0" ? "bg-red-500/10 text-red-400" : a.priority === "P1" ? "bg-orange-500/10 text-orange-400" : "bg-amber-500/10 text-amber-400"}`}>
                                {a.priority}
                              </span>
                              <span className="text-foreground flex-1 truncate">{a.message}</span>
                              {a.thread && (
                                <Link href={`/comms/thread/${a.thread.id}`} className="text-primary hover:underline truncate max-w-[200px]">
                                  {a.thread.subject}
                                </Link>
                              )}
                              <span className="text-muted-foreground">{formatDistanceToNow(new Date(a.createdAt), { addSuffix: true })}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Timeline */}
                    {inc.updates.length > 0 && (
                      <div>
                        <p className="text-xs font-medium text-muted-foreground mb-2">Timeline</p>
                        <div className="space-y-2 border-l-2 border-border pl-3 ml-1">
                          {inc.updates.map((u) => (
                            <div key={u.id} className="text-xs">
                              <p className="text-foreground">{u.content}</p>
                              <p className="text-muted-foreground">
                                {u.type !== "update" && <span className="capitalize font-medium">{u.type} · </span>}
                                {formatDistanceToNow(new Date(u.createdAt), { addSuffix: true })}
                              </p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Actions */}
                    {inc.status !== "resolved" && (
                      <div className="flex flex-wrap items-end gap-3 pt-2 border-t border-border">
                        {/* Add update */}
                        <div className="flex-1 min-w-[200px]">
                          <label className="text-xs font-medium text-muted-foreground block mb-1">Add Update</label>
                          <div className="flex gap-2">
                            <input
                              type="text"
                              value={updatingId === inc.id ? updateText : ""}
                              onFocus={() => setUpdatingId(inc.id)}
                              onChange={(e) => { setUpdatingId(inc.id); setUpdateText(e.target.value); }}
                              placeholder="Status update, workaround found..."
                              className="flex-1 h-8 rounded-md border border-input bg-background px-3 text-xs text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                            />
                            <button
                              onClick={() => handleAddUpdate(inc.id)}
                              disabled={updatingId !== inc.id || !updateText.trim()}
                              className="h-8 px-3 bg-primary text-primary-foreground rounded-md text-xs hover:bg-primary/90 disabled:opacity-50"
                            >
                              <Send size={12} />
                            </button>
                          </div>
                        </div>

                        {/* Status transitions */}
                        <div className="flex gap-2">
                          {inc.status === "active" && (
                            <button
                              onClick={() => handleStatusChange(inc.id, "monitoring")}
                              className="h-8 px-3 text-xs border border-border rounded-md hover:bg-accent/50 text-muted-foreground flex items-center gap-1"
                            >
                              <Eye size={12} /> Move to Monitoring
                            </button>
                          )}
                          <button
                            onClick={() => handleStatusChange(inc.id, "resolved")}
                            className="h-8 px-3 text-xs bg-emerald-500/10 border border-emerald-500/20 rounded-md hover:bg-emerald-500/20 text-emerald-400 flex items-center gap-1"
                          >
                            <CheckCircle2 size={12} /> Resolve
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
