-- AlterTable: Add missing token listing checklist columns to TokenReview
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "jiraTicket" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "complianceDoc" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "launchDate" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "founders" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "website" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "supportedNetworks" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "whitepaper" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "explorer" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "blockchainAnalytics" TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "travelRuleNotabene" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "priceFeedCoingecko" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "consensusMechanism" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "privacyToken" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TokenReview" ADD COLUMN IF NOT EXISTS "jurisdictionStatus" TEXT NOT NULL DEFAULT '';
