/**
 * CONFIRM register (spec §0 rule 4, §20; review remediation): every assumption
 * the build is waiting on, in one list. Cross-references the spec's §20 table
 * with the TODO(CONFIRM-*) markers in the code, so nothing assumed is silent.
 *
 *   npx tsx scripts/confirm-register.ts          write docs/phase1/confirm-register.md
 *   npx tsx scripts/confirm-register.ts --check  exit 1 if the register is out of date
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { execFileSync } from "node:child_process";

const OUT = "docs/phase1/confirm-register.md";
const SPEC = "docs/PRODUCT_SPEC.md";
const ROOTS = ["src", "prisma", "scripts", "docs", ".github", "deploy"];
const FILES = ["Dockerfile", ".env.example", "next.config.js"];
const SKIP = new Set([OUT, SPEC, "scripts/confirm-register.ts"]);
const ID = /CONFIRM-[A-Z0-9]+(?:-[A-Z0-9]+)*/g;

export interface SpecItem { ids: string[]; groups: string[][]; label: string; needed: string; blocks: string }

/** Rows of the §20 table; "CONFIRM-BANK-TEMPLATES / ACK-MINS" expands to both ids. */
export function specItems(spec: string): SpecItem[] {
  const section = spec.split(/^## 20\./m)[1]?.split(/^## 21\./m)[0] ?? "";
  const out: SpecItem[] = [];
  for (const line of section.split("\n")) {
    const cells = line.split("|").map((c) => c.trim());
    if (cells.length < 5 || !cells[1].startsWith("CONFIRM-")) continue;
    const parts = cells[1].split("/").map((p) => p.trim());
    const first = parts[0];
    const prefix = first.split("-").slice(0, 2).join("-"); // the first two segments of the row's first id
    const ids = [first, ...parts.slice(1).flatMap((p) => [`${prefix}-${p}`, `CONFIRM-${p}`])];
    // candidates per part, in order (the prefixed form first)
    const groups = [[first], ...parts.slice(1).map((p) => [`${prefix}-${p}`, `CONFIRM-${p}`])];
    out.push({ ids: [...new Set(ids)], groups, label: cells[1], needed: cells[2], blocks: cells[3] });
  }
  return out;
}

function walk(dir: string, acc: string[]) {
  if (!fs.existsSync(dir)) return;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const f = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === "node_modules" || e.name === ".next" || e.name === "fixtures") continue;
      walk(f, acc);
    } else if (/\.(ts|tsx|js|md|sql|prisma|yml|yaml|json|example)$/.test(e.name) || FILES.includes(e.name)) acc.push(f);
  }
}

/** Every git-tracked text file (so extension-less files such as CODEOWNERS are included). */
function trackedFiles(): string[] {
  try {
    return execFileSync("git", ["ls-files", "-z"], { encoding: "utf8" }).split("\0").filter(Boolean);
  } catch {
    // Not a git checkout: fall back to walking the known roots.
    const files: string[] = [];
    for (const r of ROOTS) walk(r, files);
    for (const f of FILES) if (fs.existsSync(f)) files.push(f);
    return files;
  }
}

const BINARY = /\.(png|jpe?g|gif|ico|webp|woff2?|pdf|zip|gz)$/i;

/** id → files that mention it (paths only, so the register is stable across edits). */
export function codeReferences(): Map<string, Set<string>> {
  const refs = new Map<string, Set<string>>();
  for (const f of trackedFiles()) {
    const rel = f.split(path.sep).join("/");
    if (SKIP.has(rel) || BINARY.test(rel) || rel === "package-lock.json" || !fs.existsSync(f)) continue;
    for (const m of fs.readFileSync(f, "utf8").matchAll(ID)) {
      const id = m[0].replace(/-$/, "");
      if (!refs.has(id)) refs.set(id, new Set());
      refs.get(id)!.add(rel);
    }
  }
  return refs;
}

export function render(): { markdown: string; ids: string[] } {
  const items = specItems(fs.readFileSync(SPEC, "utf8"));
  const refs = codeReferences();
  const inSpec = new Set(items.flatMap((i) => i.ids));
  const where = (id: string) => [...(refs.get(id) ?? [])].sort();
  const cell = (files: string[]) => (files.length ? files.slice(0, 4).map((f) => `\`${f}\``).join(", ") + (files.length > 4 ? ` +${files.length - 4}` : "") : "not referenced yet");

  const specRows = items.map((i) => {
    const files = [...new Set(i.ids.flatMap(where))].sort();
    // Print every id in full (searchable): per part, the candidate the code uses, else the prefixed form.
    const full = i.groups.map((g) => g.find((id) => refs.has(id)) ?? g[0]).join(", ");
    return `| ${full} | ${i.needed} | ${i.blocks} | ${cell(files)} |`;
  });
  const added = [...refs.keys()].filter((id) => !inSpec.has(id)).sort();
  const addedRows = added.map((id) => `| ${id} | ${cell(where(id))} |`);

  const markdown = `# CONFIRM register

Generated by \`scripts/confirm-register.ts\` from the spec's section 20 and the
\`TODO(CONFIRM-*)\` markers in the code. Do not edit it by hand: run
\`npx tsx scripts/confirm-register.ts\`. The test \`confirm-register-current\`
fails when a marker is added or removed without regenerating it.

Each item is an input from a person that the build is waiting on (spec §0 rule 4).
Until it is resolved, the feature it gates stays disabled or behind configuration, and
nothing is guessed. Resolving an item means: record the decision (who, when, where),
set the configuration or replace the code path, remove the marker, and regenerate
this file.

## From the spec (section 20)

| Item | What is needed | Blocks | Where the code waits for it |
|---|---|---|---|
${specRows.join("\n")}

## Added during the build (${added.length})

These came up while building and are not in the spec's section 20. Each should be
added to the spec's register, or its owner agreed, at the next spec revision.

| Item | Where |
|---|---|
${addedRows.join("\n")}
`;
  return { markdown, ids: [...new Set([...inSpec, ...refs.keys()])].sort() };
}

if (process.argv[1]?.endsWith("confirm-register.ts")) {
  const { markdown } = render();
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    if (current !== markdown) {
      console.error(`${OUT} is out of date: run npx tsx scripts/confirm-register.ts`);
      process.exit(1);
    }
    console.log(`${OUT} is current.`);
  } else {
    fs.writeFileSync(OUT, markdown);
    console.log(`Wrote ${OUT}.`);
  }
}
